dist: bionic

language: cpp
compiler: gcc
os: linux


branches:
  only:
    - master

install:
  #protoc
  - curl -L https://github.com/google/protobuf/releases/download/v3.9.0/protoc-3.9.0-linux-x86_64.zip -o /tmp/protoc.zip
  - unzip /tmp/protoc.zip -d "$HOME"/protoc
  - mkdir -p "$HOME"/src && ln -s "$HOME"/protoc "$HOME"/src/protobuf
  - sudo apt-get install libprotobuf-dev protobuf-compiler
  
env:
  - PATH=$HOME/protoc/bin:/usr/include/google:$PATH
notification:
    email: false

script: 
  - whereis protoc
  - ls -al /usr/local/include
  - ls -al /usr/local/include/google/protobuf
  - make HAS_SYSTEM_PROTOBUF=false
