dist: bionic

language: cpp
compiler: gcc
os: linux


branches:
  only:
    - master

install:
  #protoc
  - curl -L https://github.com/google/protobuf/releases/download/v3.9.1/protoc-3.9.1-linux-x86_64.zip -o /tmp/protoc.zip
  - unzip /tmp/protoc.zip -d "$HOME"/protoc
  - sudo apt-get install libprotobuf-dev protobuf-compiler
  - sudo apt-get install libprotoc-dev
  - mkdir -p "$HOME"/src && ln -s "$HOME"/protoc "$HOME"/src/protobuf
  
env:
  - PATH=$HOME/protoc/bin:$HOME/protoc/include:$PATH
notification:
    email: false

script: 
  - make all
