language: cpp
os: linux

branches:
  only:
    - master
packages:
  - gcc-7
  - g++-7
install:
  - curl -L https://github.com/google/protobuf/releases/download/v3.9.0/protoc-3.9.0-linux-x86_64.zip -o /tmp/protoc.zip
  - unzip /tmp/protoc.zip -d "$HOME"/protoc
  - mkdir -p "$HOME"/src && ln -s "$HOME"/protoc "$HOME"/src/protobuf
before_install:
  ./install-protobuf.sh

env:
  - PATH=$HOME/protoc/bin:$PATH
compiler: gcc
script: "make all"