# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    git clone https://github.com/protocolbuffers/protobuf.git
    cd protobuf
    git submodule update --init --recursive
    sh autogen.sh
    ./configure
    make
    make check
    sudo make install
    sudo ldconfig
    sh configure --prefix=/usr
    cd ..
  displayName: 'install protobuf'


- script: make all
  displayName: 'make'

